CREATE DATABASE M_GUFOS
USE M_GUFOS

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY NOT NULL
	, Nome VARCHAR(255) NOT NULL
	,Email VARCHAR(255) NOT NULL UNIQUE 
	,Senha VARCHAR(225) NOT NULL 
	,Permissao VARCHAR(255) NOT NULL 
);

CREATE TABLE Categorias(
	IdCategoria INT PRIMARY KEY IDENTITY NOT NULL --O Identity é o auto incremento--
	,Nome VARCHAR(255) NOT NULL UNIQUE 
	
);
CREATE TABLE Eventos(
	IdEvento INT PRIMARY KEY IDENTITY
	,Titulo VARCHAR(255) NOT NULL
	,Descricao TEXT
	,DataEvento DATETIME NOT NULL
	,Localizacao VARCHAR(255) NULL 
	,Ativo BIT NOT NULL DEFAULT(1)
	,IdCategoria INT FOREIGN KEY REFERENCES Categorias(IdCategoria)
);
CREATE TABLE Presencas(
	IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario)
	,IdEvento INT FOREIGN KEY REFERENCES Eventos(IdEvento)
);